development: &DEVELOPMENT
  client_id: "116925944aef40758cede9ee1886484c"
  client_secret: "44bc3bc5078e435a9105197f36be31ee"
  callback_url: "http://local.marianita.com:3000/auth/instagram/callback"

production:
  client_id: "dcfc76de2b7a4abcb96d8d34a776e816"
  client_secret: "bdbad7422d3c4b67afe4943a05d600c7"
  callback_url: "http://marianita.herokuapp.com/auth/instagram/callback"

test:
 <<: *DEVELOPMENT